"""Module 5 — Family Engagement & Emergency models.

Tables:
- family_digests:   daily summary of patient activity, sent at 8 PM
- sos_alerts:       emergency triggers from patient (with location)
- caregiver_threads: chat thread per patient (one per patient)
- caregiver_messages: messages in a thread

Messaging is GROUP — all linked contacts see same thread.
"""
import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean, Column, DateTime, Enum, Float, ForeignKey, Integer, String, Text,
)

from app.core.database import Base


def _uuid() -> str:
    return str(uuid.uuid4())


SOS_STATUSES = ("ACTIVE", "ACKNOWLEDGED", "RESOLVED", "FALSE_ALARM")
DIGEST_STATUSES = ("PENDING", "SENT", "FAILED")


# ─── Family Digest ───────────────────────────────────────────────────────────
class FamilyDigest(Base):
    """A daily summary of the patient's day — generated automatically.

    Generated by the scheduler at 8 PM local. Body is plain text (markdown-ish);
    delivery_meta tracks email status.
    """
    __tablename__ = "family_digests"

    id          = Column(String(36), primary_key=True, default=_uuid)
    patient_id  = Column(String(36), ForeignKey("users.id", ondelete="CASCADE"),
                         nullable=False, index=True)

    period_date = Column(String(10), nullable=False)   # YYYY-MM-DD covered

    # Aggregated metrics (denormalized — fast to display)
    activities_count    = Column(Integer, default=0)
    medications_taken   = Column(Integer, default=0)
    medications_total   = Column(Integer, default=0)
    avg_mood            = Column(Float, nullable=True)
    fall_alerts         = Column(Integer, default=0)

    body_text   = Column(Text, nullable=False)         # markdown-style
    body_html   = Column(Text, nullable=True)

    status      = Column(Enum(*DIGEST_STATUSES, name="digest_status"),
                         nullable=False, default="PENDING", index=True)
    recipients_count = Column(Integer, default=0)
    sent_at     = Column(DateTime, nullable=True)
    error_msg   = Column(String(500), nullable=True)

    created_at  = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


# ─── SOS Alert ───────────────────────────────────────────────────────────────
class SOSAlert(Base):
    """Emergency button press by patient.

    Notifies ALL linked contacts (doctors + family) immediately via:
    - in-app notification
    - browser notification (if granted)
    - email (if SMTP configured)
    - SMS (if Twilio configured)

    Lifecycle: ACTIVE → ACKNOWLEDGED (someone clicked) → RESOLVED (patient OK)
    """
    __tablename__ = "sos_alerts"

    id              = Column(String(36), primary_key=True, default=_uuid)
    patient_id      = Column(String(36), ForeignKey("users.id", ondelete="CASCADE"),
                             nullable=False, index=True)

    message         = Column(String(500), nullable=True)   # patient's optional message
    latitude        = Column(Float, nullable=True)
    longitude       = Column(Float, nullable=True)
    location_text   = Column(String(500), nullable=True)

    status          = Column(Enum(*SOS_STATUSES, name="sos_status"),
                             nullable=False, default="ACTIVE", index=True)
    triggered_at    = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    acknowledged_by_user_id = Column(String(36), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    acknowledged_by_name    = Column(String(255), nullable=True)
    acknowledged_at         = Column(DateTime, nullable=True)

    resolved_at     = Column(DateTime, nullable=True)
    resolution_note = Column(Text, nullable=True)

    # How notifications were dispatched (denormalized stats)
    notified_count       = Column(Integer, default=0)
    sms_sent             = Column(Boolean, default=False)
    sms_failed_reason    = Column(String(500), nullable=True)


# ─── Caregiver Messaging ─────────────────────────────────────────────────────
class CaregiverThread(Base):
    """One thread per patient — group chat among patient + linked contacts.

    Created lazily on first message. Thread members = patient + everyone
    in patient_links for that patient.
    """
    __tablename__ = "caregiver_threads"

    id          = Column(String(36), primary_key=True, default=_uuid)
    patient_id  = Column(String(36), ForeignKey("users.id", ondelete="CASCADE"),
                         nullable=False, unique=True, index=True)
    title       = Column(String(255), nullable=True)
    created_at  = Column(DateTime, default=datetime.utcnow, nullable=False)
    last_message_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class CaregiverMessage(Base):
    __tablename__ = "caregiver_messages"

    id          = Column(String(36), primary_key=True, default=_uuid)
    thread_id   = Column(String(36), ForeignKey("caregiver_threads.id", ondelete="CASCADE"),
                         nullable=False, index=True)
    sender_id   = Column(String(36), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    sender_name = Column(String(255), nullable=False)
    sender_role = Column(String(20), nullable=False)
    content     = Column(Text, nullable=False)
    created_at  = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
